export enum ErrorType {
  AuthorNotFound = "AuthorNotFound",
  BadGateway = "BadGateway",
  BadRequest = "BadRequest",
  Conflict = "Conflict",
  Forbidden = "Forbidden",
  GatewayTimeOut = "GatewayTimeOut",
  InternalServerError = "InternalServerError",
  LabelAlreadyExists = "LabelAlreadyExists",
  LabelNotFound = "LabelNotFound",
  NotFound = "NotFound",
  NotImplemented = "NotImplemented",
  ResourceLocked = "ResourceLocked",
  RequestTimeout = "RequestTimeout",
  ServiceUnavailable = "ServiceUnavailable",
  SomethingWentWrong = "SomethingWentWrong",
  Unauthorized = "Unauthorized",
  UnexpectedServerError = "UnexpectedServerError",
  UnprocessableContent = "UnprocessableContent",
}
